# Generated by Django 4.2.15 on 2024-09-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
        migrations.AddField(
            model_name='teacher',
            name='tscNumber',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
