# Generated by Django 4.2.15 on 2024-09-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teacher_age_teacher_tscnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
