# Generated by Django 4.2.15 on 2024-09-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_course_student_course'),
        ('teacher', '0003_remove_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(to='student.course'),
        ),
    ]
