# Generated by Django 4.2.15 on 2024-09-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0002_rename_employee_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('department', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ems_app.department')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ems_app.department'),
        ),
    ]
