# Generated by Django 4.2.15 on 2024-09-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0005_remove_employee_department_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='profileImage',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
